force-app/main/default/objects/Callout_Configuration__mdt/Callout_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Contains configuration for callouts so that values aren&apos;t hard coded in the code.</description>
    <label>Callout Configuration</label>
    <pluralLabel>Callout Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Callout_Configuration__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Http Method for the callout</description>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Callout_Configuration__mdt/fields/Named_Credential_Name__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential_Name__c</fullName>
    <description>The Name of the Named Credential.</description>
    <label>Named Credential Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Callout_Configuration__mdt/fields/Static_Base_URL_Addition__c.field-meta.xml
<CustomField>
    <fullName>Static_Base_URL_Addition__c</fullName>
    <description>Static value to add to the Base URL configured in the Named Credential.</description>
    <label>Static Base URL Addition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CalloutConfigurationsSelector.cls
public with sharing class CalloutConfigurationsSelector {

    public static Callout_Configuration__mdt getSingleConfigBasedOnDeveloperName(String calloutConfigDeveloperName) {

        Callout_Configuration__mdt calloutConfig = [
            SELECT Id, DeveloperName, Named_Credential_Name__c, Static_Base_URL_Addition__c, Method__c
            FROM Callout_Configuration__mdt
            WHERE DeveloperName = :calloutConfigDeveloperName
            LIMIT 1
        ];
        return calloutConfig;
    }
}